@startuml

class Either<L,R> {
    - L Left
    - R Right

    .. factory methods ..
    + {static} <L,R> Either<L,R> left(L value)
    + {static} <L,R> Either<L,R> right(R value)
    .. executors ..
    + {static} <T,R> Function<T, Either> lift(CheckedFunction<T,R> function)
    + {static} <T,R> Function<T, Either> liftWithValue(CheckedFunction<T,R> function)
    .. accessors ..
    + Optional<L> getLeft()
    + Optional<R> getRight()
    + boolean isLeft()
    + boolean isRight()
}

@enduml